### ISSUE TITLE
Values parser should not use PostCSS core classes

### ISSUE THREAD

**Issue by ai** [shellscape/postcss-values-parser#103]
Every parser is unique. I understand that you want to reduce your code and have similar PostCSS’s `append()`, etc API. But in addition to simple functions like `append`, PostCSS classes have a lot of internal hacks.

By extending PostCSS’s classes you can start to use private API, which can change in patch releases.

For instance, it happens with PostCSS 7.0.20 fix https://github.com/postcss/postcss/issues/1305

I recommend just copy-paste PostCSS functions in your own classes. It is OK for cases, where you have AST for different things.

**Comment by shellscape** [comment]
I appreciate the heads up, but this is not something I want to do. I moved from copy/paste to leveraging PostCSS core because the maintenance burden was too great. I understand that you owned the reported bug as a problem with PostCSS, but it was a problem with this module because it uses PostCSS. Sometimes we depend on a bugs in a public API that get fix, and then break our dependence on a bug. That's not PostCSS's fault. The next time that happens, redirect the reporter over here and we'll update to correct on this end.
