### ISSUE TITLE
Is this a PR or a v2

### ISSUE THREAD

**Issue by jonathantneal** [shellscape/postcss-values-parser#14]
Fantastic work on this parser; I could foresee it becoming the defacto standard. I’m inviting you and other PostCSS developers and advocates to chime in on my prompt. Sincerely, I hope not to provoke any harsh feelings.

I see you opened [an issue with postcss-value-parser](https://github.com/TrySound/postcss-value-parser/issues/26) which presented your concerns regarding helper methods and raws, as well as a motivation to seeing it “integrating this into the main parser [of PostCSS]”. Those are all good goals, and I think you’ve met them in this project. It’s unfortunate the discussion ended there and you closed the issue a week later, only because it’s possible @TrySound did not have a chance to review it.

Moving forward, what might we do to help coalesce the PostCSS ecosystem here? Since your plugins are not fundamentally attempting to do different things or things in different ways, would the ideal scenario be that postcss-values-parser be merged back into postcss-value-parser, or that postcss-value-parser be deprecated?

I also want to acknowledge that project ownership may be another factor. postcss-values-parser may have become in-house work that must remain in-house. Conversely, @TrySound may not be interested in these changes. All that is fair; I’d just like to know how you all think we should proceed here (and in related matters going forward), as interested users of the ecosystem?

Thanks for reviewing this!

**Comment by shellscape** [comment]
thanks much, and no worries about the feels and whatnot. you could call it crap and I'd just be all [yeah well that's just like your opinion man](https://www.youtube.com/watch?v=pWdd6_ZxX8c) :) 

yeah, I was a bit impatient on that issue I opened with the other project. for smaller projects I figure that a lack of response after a solid week usually indicates some really busy ownership or low priority. that and the immediate need for the Lesshint project and our effort to convert to postcss from gonzales-pe were the determining factors to knock something else out. I personally view this project to be superior in function to value-parser, but I'm clearly biased. If it were my call, I'd deprecate value-parser - not at all a knock on the project but rather how I see their differences.

There's really no in-house concerns; it lives under the Lesshint org because it made sense at the time for it to be there. I'm all for some convergence with PostCSS proper. But I make no assumptions as to what the folks behind value-parser and PostCSS prefer there.

**Comment by shellscape** [comment]
@jonathantneal I'm gonna close this purely for organizational means. if you'd like to reopen it, please do let me know.
