### ISSUE TITLE
Hyphen in prefixed values gets parsed as operator node when in loose mode

### ISSUE THREAD

**Issue by jwilsson** [shellscape/postcss-values-parser#38]
_Originally reported at https://github.com/lesshint/lesshint/issues/433_

* Node Version: `8.5.0`
* NPM Version: `5.4.2`
* postcss-values-parser Version: `1.3.0`

This issue is regarding a problem with:
- [x] Standard CSS
- [ ] LESS
- [ ] SCSS
- [ ] SASS

If you have a large amount of code to share which demonstrates the problem you're experiencing, please provide a link to your
repository rather than pasting code. Otherwise, please paste relevant short snippets below.

```css
opacity -webkit-filter
```

### Expected Behavior
An AST similar to this:

```
Word {
  value: 'opacity',
  ...
}
Word {
  value: '-webkit-filter'
  ...
}
```
### Actual Behavior
This AST:

```
Word {
  value: 'opacity',
  ...
}
Operator {
  value: '-',
  ...
}
Word {
  value: 'webkit-filter',
  ...
}
```

### How can we reproduce the behavior?
```js
const parser = require('postcss-values-parser');
const ast = parser('opacity -webkit-filter', {
    loose: true,
}).parse();

ast.walk((node) => {
    console.log(node);
});
```

The issue is only present in `loose` mode. In the regular/strict mode it works as expected. It also seems to work as expected when the prefixed value is the first one, but when it's the second (or more) it starts emitting `operator` nodes.

**Comment by shellscape** [comment]
This makes me die a little inside 😆 the operators are such a pain in the butt

**Comment by jwilsson** [comment]
Oh, btw. I forgot to mention. I think @donotknow might be interested in submitting a fix, right?

**Comment by shellscape** [comment]
@jwilsson would looooove a fix PR

**Comment by jwilsson** [comment]
@shellscape Hmm, I'll see if I can figure it out 😁

**Comment by donotknow** [comment]
So this seems to be because of the difference between loose/non-loose here:

https://github.com/shellscape/postcss-values-parser/blob/master/lib/parser.js#L177-L187

```js
      if (!this.options.loose) {
        if (this.nextToken[0] === 'word') {
          return this.word();
        }
      }
      else {
        if ((!this.current.nodes.length || (this.current.last && this.current.last.type === 'operator')) && this.nextToken[0] === 'word') {
          return this.word();
        }
      }
    }
```

@jwilsson @shellscape I read through the associated history (PR #24 over here and https://github.com/lesshint/lesshint/issues/340 over on lesshint) it seems like that was just restored to maintain lesshint’s old functionality. The new (and improved) postcss-values-parser seems to be more correct (`+5` is a number, it’s just a positive number; it’s not an operator & number combination).

And then just update on the lesshint’s side to account for that in the spaceAroundOperator which is the thing that should be checking the spaces within that number based on it’s sibling nodes instead of relying on it being an operator.

So! I’m going to create some PRs to explain myself a little, which’ll be easier in code I think.

**Comment by shellscape** [comment]
@jwilsson @donotknow I'm undertaking a rewrite of the module using the base tokenizer from PostCSS. should make this module a lot easier to maintain going forward, and should help to provide a path to solve this kind of issue easily. I'll keep you posted on progress.

**Comment by shellscape** [comment]
@jwilsson check the `next` branch for progress. Will be pushing a commit tonight that should make this issue moot.

**Comment by shellscape** [comment]
Happy to report that the offending css value passes in the `next` branch. I'll be releasing a beta of 3.0.0 later today. Thanks for reporting the issue. Cheers 🍻
